//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        public int MonHocID { get; set; }
        public string MonHocName { get; set; }
        public string Diem15 { get; set; }
        public string Diem45 { get; set; }
        public string DiemTB { get; set; }
    }
}
